name = "SurvivalModels"
uuid = "48cbd7fc-4c60-4391-acb4-447ee80706a8"
authors = ["Aidan Saavedra Buckley"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
